import Head from "next/head";
import Link from "next/link";

const items = ["Task 1", "Task 2", "Task 3"];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center p-4">
        <div className="container">
          <h1 className="font-extrabold text-black text-5xl">Tasks</h1>
          {items.length === 0 && <div className="pt-2">
            <div>Enter task</div>
          </div>}
          {items && <div className="pt-2">
            {items.map((item, idx) => (
              <div key={idx}>{item}</div>
            ))}
          </div>}
        </div>
      </main>
    </>
  );
}
